[build]
  command = "npm run build"
  publish = ".next"


[build.environment]
CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"


[[plugins]]
  package = "netlify-plugin-cypress"